var title = "My first console project";
console.log(title);
var first_name = "Nithish";
var last_name = "prakash";
var full_name = first_name.concat(last.name);
console.log(full_name);
var number1 = 12;
console.log(number1);
var number2 = 23;
console.log(number2);
var plus = number1+number2;
console.log(plus);
var subtractedby = number1-number2;
console.log(subtractedby);
var multipliedby = number1*number2;
console.log(multipliedby);
var dividedby = number1/number2;
console.log(dividedby);